project_id = "pcaebfncvuvdguyjmyxm"

[functions.refine-prompt]
verify_jwt = false

[functions.stripe-sync]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = true

[functions.create-billing-plan]
verify_jwt = false

[functions.update-billing-plan]
verify_jwt = false

[functions.stripe-sync-products]
verify_jwt = false

[functions.stripe-test-connection]
verify_jwt = false
